# Generated by Django 4.2.27 on 2025-12-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='icon', max_length=50),
            preserve_default=False,
        ),
    ]
