# Generated by Django 4.2.27 on 2025-12-23 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringpayment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 12, 23)),
            preserve_default=False,
        ),
    ]
