# Generated by Django 4.2.27 on 2025-12-24 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_recurringpayment_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.family')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_expenses', to='core.month')),
            ],
            options={
                'unique_together': {('month', 'category')},
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='planned_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.plannedexpense'),
        ),
    ]
