# Generated by Django 4.2.27 on 2025-12-27 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_plannedexpense_expense_planned_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringpayment',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_payments', to='core.category'),
            preserve_default=False,
        ),
    ]
