# Generated by Django 4.2.27 on 2025-12-27 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db import migrations


def migrate_planned_expenses_to_plans(apps, schema_editor):
    PlannedExpense = apps.get_model("core", "PlannedExpense")
    PlannedExpensePlan = apps.get_model("core", "PlannedExpensePlan")
    PlannedExpenseVersion = apps.get_model("core", "PlannedExpenseVersion")

    for pe in PlannedExpense.objects.all():
        plan = PlannedExpensePlan.objects.create(
            family=pe.family,
            category=pe.category,
            name=pe.name or pe.category.name,
            plan_type="ONE_MONTH",
            active=True,
            start_month=pe.month,
            end_month=pe.month,
            created_by=pe.created_by,
        )

        PlannedExpenseVersion.objects.create(
            plan=plan,
            planned_amount=pe.planned_amount,
            valid_from=pe.month,
            valid_to=pe.month,
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_recurringpayment_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedExpensePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('plan_type', models.CharField(choices=[('ONE_MONTH', 'Sólo un mes'), ('ONGOING', 'Mantener en el tiempo')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('end_month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planned_plans_ending', to='core.month')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.family')),
                ('start_month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_plans_starting', to='core.month')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedExpenseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.plannedexpenseplan')),
                ('valid_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_versions_from', to='core.month')),
                ('valid_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planned_versions_to', to='core.month')),
            ],
            options={
                'ordering': ['valid_from'],
            },
        ),
        migrations.RunPython(migrate_planned_expenses_to_plans),
    ]
