# Generated by Django 4.2.27 on 2026-02-23 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_migrate_planned_expenses_to_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('plan_type', models.CharField(choices=[('ONE_MONTH', 'Sólo un mes'), ('ONGOING', 'Mantener en el tiempo')], max_length=10)),
                ('due_day', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('end_month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_plans_ending', to='core.month')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.family')),
                ('start_month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_plans_starting', to='core.month')),
            ],
        ),
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.category'),
        ),
        migrations.CreateModel(
            name='IncomePlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.incomeplan')),
                ('valid_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_versions_from', to='core.month')),
                ('valid_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_versions_to', to='core.month')),
            ],
            options={
                'ordering': ['valid_from'],
            },
        ),
        migrations.AddField(
            model_name='income',
            name='income_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_incomes', to='core.incomeplan'),
        ),
    ]
