# Generated by Django 4.2.27 on 2026-02-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_incomeplan_income_description_alter_income_category_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['month', 'income_plan'], name='idx_income_month_plan'),
        ),
        migrations.AddConstraint(
            model_name='income',
            constraint=models.UniqueConstraint(condition=models.Q(('income_plan__isnull', False)), fields=('month', 'income_plan'), name='uniq_income_per_month_per_income_plan'),
        ),
    ]
